name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
          cache: true
      
      - name: Create local.properties
        run: |
          touch android/local.properties
          echo "flutter.sdk=$GITHUB_WORKSPACE/flutter" > android/local.properties
          
      - name: Install dependencies
        run: |
          flutter pub get
          flutter clean
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Generate debug keystore
        run: |
          cd android/app
          keytool -genkeypair \
            -keystore debug.keystore \
            -storepass android \
            -keypass android \
            -alias androiddebugkey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US" \
            -storetype PKCS12
          cd ../..
      
      - name: Build APK
        run: |
          flutter build apk --release --split-per-abi
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            Flutter Clock App Release
            
            Features:
            - Digital Clock with 12/24 hour format
            - Date display
            - Countdown timer
            - Dark/Light theme
            
            APK Files:
            - app-arm64-v8a-release.apk (for modern Android devices)
            - app-armeabi-v7a-release.apk (for older Android devices)
            - app-x86_64-release.apk (for Android emulators)
